# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170308_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='average',
            new_name='slug',
        ),
    ]
