# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170309_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='slug',
            new_name='name',
        ),
    ]
